### ISSUE TITLE
Firewall rules are not preserved across reboot when using the Iptables Add-On

### ISSUE THREAD

**Issue by Gusymochis** [replicatedhq/kurl.sh#505]
When using the iptables add-on on a kURL installer will add the rules, but a reboot will scrape those away.
To replicate create an installer file and add iptables addon with rules:
```yaml
iptablesConfig:
    iptablesCmds:
      - ["-A", "INPUT", "-p", "TCP", "--dport", "1234", "-j", "REJECT"]
    preserveConfig: false
```
1. Use the installer to create a k8s deployment.
2. Check iptables with `sudo iptables -L` to verify port **1234** is blocked.
3. Reboot node.
4. Check iptable with `sudo iptables -L` port  **1234** will no longer be blocked.
